
export const fonts={
    TAJAWALREGULAR: "Tajawal-Regular",
    TAJAWALEXTRABOLD:"Tajawal-ExtraBold",
    CAIROBLACK:"Cairo-Bold",
    CAIROBOLD: "Cairo-ExtraBold",
    CAIROEXTRABOLD: "Cairo-ExtraLight",
    CAIROEXTRLIGHK:"Cairo-Light",
    CAIROMEDIUM:"Cairo-Medium",
    CAIROREGULARK:"Cairo-Regular",
    CAIROSEMILBOLD:"Cairo-SemiBold",
    CAIROVARIABLEFON:"Cairo-VariableFont_slnt,wght",
    CAIROCHANGA:"Changa-Bold",
    EXTRABOLD:"Changa-ExtraBold",
    EXTRALIGHT:"Changa-ExtraLight",
    CHANGALIGHT:"Changa-Light",
    CHANGAMEDIUM:"Changa-Medium",
    CHANGAREGULAR:"Changa-Regular",
    CHANGASEMIBOLD:"Changa-SemiBold",
    CHANGAVARIABLEFONT:"Changa-VariableFont_wght",
    COURGETTE:'Courgette-Regular',
    COURGETTR:'Creepster-Regular',
    ACME:"Acme-Regular",
    HANDLEE:"Handlee-Regular",
}